ibw_affiliate:
    path:     /
    defaults: { _controller: "IbwJobeetBundle:Affiliate:index" }

ibw_affiliate_show:
    path:     /{id}/show
    defaults: { _controller: "IbwJobeetBundle:Affiliate:show" }

ibw_affiliate_new:
    path:     /new
    defaults: { _controller: "IbwJobeetBundle:Affiliate:new" }

ibw_affiliate_create:
    path:     /create
    defaults: { _controller: "IbwJobeetBundle:Affiliate:create" }
    methods:  POST

ibw_affiliate_wait:
    path:     /wait
    defaults: { _controller: "IbwJobeetBundle:Affiliate:wait" }

ibw_affiliate_edit:
    path:     /{id}/edit
    defaults: { _controller: "IbwJobeetBundle:Affiliate:edit" }

ibw_affiliate_update:
    path:     /{id}/update
    defaults: { _controller: "IbwJobeetBundle:Affiliate:update" }
    methods:  [POST, PUT]

ibw_affiliate_delete:
    path:     /{id}/delete
    defaults: { _controller: "IbwJobeetBundle:Affiliate:delete" }
    methods:  [POST, DELETE]
