ibw_job:
    path:     /
    defaults: { _controller: "IbwJobeetBundle:Job:index" }

ibw_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "IbwJobeetBundle:Job:show" }
    requirements:
        id: \d+

ibw_job_preview:
    path:     /{company}/{location}/{token}/{position}
    defaults: { _controller: "IbwJobeetBundle:Job:preview" }
    requirements:
        token: \w+

ibw_job_publish:
    path:     /{token}/publish
    defaults: { _controller: "IbwJobeetBundle:Job:publish" }
    requirements: { _method: post }

ibw_job_new:
    path:     /new
    defaults: { _controller: "IbwJobeetBundle:Job:new" }

ibw_job_create:
    path:     /create
    defaults: { _controller: "IbwJobeetBundle:Job:create" }
    methods:  POST

ibw_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "IbwJobeetBundle:Job:edit" }

ibw_job_update:
    path:     /{token}/update
    defaults: { _controller: "IbwJobeetBundle:Job:update" }
    requirements: { _method: post|put }

ibw_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "IbwJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }

ibw_job_extend:
    path:     /{token}/extend
    defaults: { _controller: "IbwJobeetBundle:Job:extend" }
    requirements: { _method: post }

ibw_job_search:
    path:     /search
    defaults: { _controller: "IbwJobeetBundle:Job:search" }

ibw_job_favourite:
    path:     /{id}/favourite
    defaults: { _controller: "IbwJobeetBundle:Job:favourite" }
    methods:  POST
